cinema_aliases:
  Vika:
    - "Vika Kino"
    - "vika"
    - "vika kino"
  Cinemateket:
    - "cinemateket"
  Vega:
    - "vega"
    - "vega scene"
  Klingenberg: 
    - "klingenberg"

travel_times:
  # Cinemateket (Dronningens gate) <-> Vika Kino (Vika)
  - from: "Cinemateket"
    to: "Vika"
    minutes: 20
  
  - from: "Vika"
    to: "Cinemateket"
    minutes: 20
  
  # Cinemateket (Dronningens gate) <-> Vega (Torggata)
  - from: "Cinemateket"
    to: "Vega"
    minutes: 20
  
  - from: "Vega"
    to: "Cinemateket"
    minutes: 20
  
  # Vika Kino (Vika) <-> Vega (Torggata)
  # Requires a bicycle, otherwise it's 25 minutes walking
  - from: "Vika"
    to: "Vega"
    minutes: 15
  
  - from: "Vega"
    to: "Vika"
    minutes: 15

  # It's a special one-off
  - from: "Klingenberg"
    to: "Klingenberg"
    minutes: 0
