seen:
- title: Åpning // Koreansk Kulturdag
  date:
- title: Oldboy
  date:
weights:
- title: SØRprise
  start_time: '2025-11-09T18:15:00'
  weight: 10.0
- title: Joint Security Area
  start_time:
  weight: 1.1
- title: North South Man Woman
  start_time:
  weight: 1.2
- title: Bare et uhell (It Was Just an Accident)
  start_time:
  weight: 1.1
- title: Return to Seoul
  start_time:
  weight: 1.1
